os:
  - linux
language: python
python:
  - "3.4"
  - "3.3"
  - "3.5"
  - "2.7"
  - "2.6"


before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install grequests requests requests_cache
  - pip install easydev>=0.9.7 beautifulsoup4 suds-jurko appdirs
  - pip install coveralls nose numpydoc sphinx-gallery
# # command to run tests, e.g. python setup.py test
script:
  - python setup.py nosetests  --with-coverage --cover-package bioservices --logging-level ERROR --attr '!slow,!skip,!fixme,!skip_travis'

after_success:
  coveralls
