language: python
python:
  - "3.3"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install .
  - pip install nose coverage
    grequests requests requests_cache easydev>=0.7.2 beautifulsoup4 suds-jurko appdirs
  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:  
  - python setup.py nosetests --with-coverage --cover-package bioservices --logging-level ERROR

after_success:
  coveralls
