os:
  - linux
language: python
cache:
   directories:
     - $HOME/.cache/pip

python:
  - "3.4"
  - "3.3"
  - "3.5"
  - "2.7"
  - "2.6"


before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install grequests requests requests_cache
  - pip install easydev>=0.9.34 beautifulsoup4 suds-jurko appdirs
  - pip install coveralls coverage numpydoc sphinx-gallery
  - pip install pytest pytest-cov pytest-xdist pytest-mock pytest-timeout
  - pip install .
# # command to run tests, e.g. python setup.py test
script:
  - pytest -v --durations=60 test/ --cov=bioservices --cov-report term --timeout 300 -n 4 

after_success:
  coveralls
