name: gdsctools_env

channels:
- bioconda
- defaults
- r
- conda-forge

dependencies:
- requests
- grequests
- numpy
- pandas
- matplotlib
- scipy
- pip:
  - sphinx-gallery
  - matplotlib
  - easydev>=0.9.21
  - bioservices
