name: gdsctools_env

channels:
- bioconda
- defaults
- r
- conda-forge

dependencies:
- python=3.5.0
- requests
- grequests
- numpy
- pandas
- matplotlib
- scipy
- sphinx
- numpydoc
- suds-jurko
- pip:
  - sphinx-gallery
  - matplotlib
  - easydev>=0.9.21
  - bioservices
