name: gdsctools_env

channels:
- bioconda
- defaults
- r
- conda-forge

dependencies:
- python=3.5.0
- requests
- grequests
- numpy
- matplotlib
- scipy
- easydev>=0.9.34
- sphinx
- numpydoc
- pip
- suds-jurko
- pip:
  - sphinx-gallery
  - bioservices
  # docutils failed june 2018 maybe time to remove it from here
  #- docutils<0.13.1 # https://github.com/sphinx-doc/sphinx/issues/3212
